apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: first-deployment
  name: first-deployment
  namespace: cka-training
spec:
  containers:
  - image: nginx
    name: first-deployment
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
