apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
    tier: backend
  name: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: backend
  strategy: {}
  template:
    metadata:
      labels:
        app: mysql
        tier: backend
    spec:
      containers:
      - image: hshar/mysql:5.5
        name: mysql-db
        ports:
        - containerPort: 3306
        resources: {}
status: {}
