apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp-sql1
    tier: backend
  name: webapp-sql1
spec:
  clusterIP: None
  ports:
  - name: "3306"
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: webapp-sql1
    tier: backend
  type: ClusterIP
status:
  loadBalancer: {}
